name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '5.7/**'
      - '8.0/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [5.7, 8.0]
        include:
          - version: 5.7
            docker-context: 5.7/debian/default
            docker-tags: |
              nicoherbigde/mysql:5.7
              nicoherbigio/mysql:5.7
              nicoherbigde/mysql:5.7.40
              nicoherbigio/mysql:5.7.40
          - version: 8.0
            docker-context: 8.0/debian/default
            docker-tags: |
              nicoherbigde/mysql:8.0
              nicoherbigio/mysql:8.0
              nicoherbigde/mysql:8.0.30
              nicoherbigio/mysql:8.0.30

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
